In [1]:
# pip install plotly
!pip install kagglehub

DEPRECATION: Loading egg at c:\users\thoma\appdata\local\programs\python\python312\lib\site-packages\mlproject-0.0.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: kagglehub in c:\users\thoma\appdata\local\programs\python\python312\lib\site-packages (0.3.3)
Requirement already satisfied: packaging in c:\users\thoma\appdata\roaming\python\python312\site-packages (from kagglehub) (24.0)
Requirement already satisfied: requests in c:\users\thoma\appdata\local\programs\python\python312\lib\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\thoma\appdata\local\programs\python\python312\lib\site-packages (from kagglehub) (4.66.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\thoma\appdata\local\programs\python\python312\lib\site-packages (from requests->kagglehub) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\thoma\appdata\local\programs\python\python312\lib\site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\thoma\appdata\local\programs\python\python312\lib\site-packages (from requests->kagglehub) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\thoma\appdata\local\programs\python\python312\lib\site-packages (from requests->kagglehub) (2024.8.30)
Requirement already satisfied: colorama in c:\users\thoma\appdata\roaming\python\python312\site-packages (from tqdm->kagglehub) (0.4.6)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px  # Corrected this line
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline

In [3]:
import kagglehub

# Download latest version
df = kagglehub.dataset_download("susant4learning/holiday-package-purchase-prediction")

print("Path to dataset files:", df)

Path to dataset files: C:\Users\thoma\.cache\kagglehub\datasets\susant4learning\holiday-package-purchase-prediction\versions\1

In [4]:
df

'C:\\Users\\thoma\\.cache\\kagglehub\\datasets\\susant4learning\\holiday-package-purchase-prediction\\versions\\1'

In [5]:
df = pd.read_csv(R"D:\Data Science Projects\archive\Travel.csv")
df

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

In [6]:
#dATA cLEANING
#handling missing values
#check data type
#Understand the dataset
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [7]:
df.describe()

,CustomerID,ProdTaken,Age,CityTier,DurationOfPitch,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,MonthlyIncome
count,4888.000000,4888.000000,4662.000000,4888.000000,4637.000000,4888.000000,4843.000000,4862.000000,4748.000000,4888.000000,4888.000000,4888.000000,4822.000000,4655.000000
mean,202443.500000,0.188216,37.622265,1.654255,15.490835,2.905074,3.708445,3.581037,3.236521,0.290917,3.078151,0.620295,1.187267,23619.853491
std,1411.188388,0.390925,9.316387,0.916583,8.519643,0.724891,1.002509,0.798009,1.849019,0.454232,1.365792,0.485363,0.857861,5380.698361
min,200000.000000,0.000000,18.000000,1.000000,5.000000,1.000000,1.000000,3.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1000.000000
25%,201221.750000,0.000000,31.000000,1.000000,9.000000,2.000000,3.000000,3.000000,2.000000,0.000000,2.000000,0.000000,1.000000,20346.000000
50%,202443.500000,0.000000,36.000000,1.000000,13.000000,3.000000,4.000000,3.000000,3.000000,0.000000,3.000000,1.000000,1.000000,22347.000000
75%,203665.250000,0.000000,44.000000,3.000000,20.000000,3.000000,4.000000,4.000000,4.000000,1.000000,4.000000,1.000000,2.000000,25571.000000
max,204887.000000,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,5.000000,1.000000,3.000000,98678.000000

In [8]:
#Check all the categories
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [9]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [10]:
df['Gender'] = df['Gender'].replace('Fe Male','Female')
df['MaritalStatus'] = df['MaritalStatus'].replace('Single', 'Unmarried')

In [11]:
#cHECK Missing values
Features_with_nan = [features for features in df.columns if df[features].isnull().sum()>=1]
for feature in Features_with_nan:
    print(feature,np.round(df[feature].isnull().mean()*100,5),'has % missing values')

Age 4.62357 has % missing values
TypeofContact 0.51146 has % missing values
DurationOfPitch 5.13502 has % missing values
NumberOfFollowups 0.92062 has % missing values
PreferredPropertyStar 0.53191 has % missing values
NumberOfTrips 2.86416 has % missing values
NumberOfChildrenVisiting 1.35025 has % missing values
MonthlyIncome 4.76678 has % missing values

In [12]:
#Statistics on numerical columns 
df[Features_with_nan].select_dtypes(exclude='object').describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

In [13]:
#Imputing Null values
for col in df[Features_with_nan].columns:
    if df[col].dtype == 'object':
        df[col].fillna(df[col].mode()[0], inplace = True)
    else:
        df[col].fillna(df[col].median(), inplace = True)

In [14]:
df[Features_with_nan].isna().sum()

Age                         0
TypeofContact               0
DurationOfPitch             0
NumberOfFollowups           0
PreferredPropertyStar       0
NumberOfTrips               0
NumberOfChildrenVisiting    0
MonthlyIncome               0
dtype: int64

In [15]:
df.drop('CustomerID', axis = 1, inplace=True)

In [16]:
df['ProdTaken'].value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [17]:
df.columns.to_list()

['ProdTaken',
 'Age',
 'TypeofContact',
 'CityTier',
 'DurationOfPitch',
 'Occupation',
 'Gender',
 'NumberOfPersonVisiting',
 'NumberOfFollowups',
 'ProductPitched',
 'PreferredPropertyStar',
 'MaritalStatus',
 'NumberOfTrips',
 'Passport',
 'PitchSatisfactionScore',
 'OwnCar',
 'NumberOfChildrenVisiting',
 'Designation',
 'MonthlyIncome']

In [18]:
df.dtypes

ProdTaken                     int64
Age                         float64
TypeofContact                object
CityTier                      int64
DurationOfPitch             float64
Occupation                   object
Gender                       object
NumberOfPersonVisiting        int64
NumberOfFollowups           float64
ProductPitched               object
PreferredPropertyStar       float64
MaritalStatus                object
NumberOfTrips               float64
Passport                      int64
PitchSatisfactionScore        int64
OwnCar                        int64
NumberOfChildrenVisiting    float64
Designation                  object
MonthlyIncome               float64
dtype: object

In [19]:
df['NumberOfChildrenVisiting'].dtypes

dtype('float64')

In [20]:
# Ensure column is numeric, convert errors to NaN
df['NumberOfChildrenVisiting'] = pd.to_numeric(df['NumberOfChildrenVisiting'], errors='coerce')

# Fill NaN values with 0 (or other value if appropriate), then convert to int
df['NumberOfChildrenVisiting'] = df['NumberOfChildrenVisiting'].fillna(0).astype('int64')

In [21]:
#Create a new fearure fo
df['TotalVisiting'] = df['NumberOfPersonVisiting'] + df['NumberOfChildrenVisiting']
df.drop(columns=['NumberOfPersonVisiting','NumberOfChildrenVisiting'], axis = 1, inplace=True)

In [22]:
#Get all the numeric features
num_features = [feature for feature in df.columns if df[feature].dtype!='O']
print('Num of numerical features:', len(num_features))

Num of numerical features: 12

In [23]:
#Get all the numeric features
cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print('Num of categorical features:', len(cat_features))

Num of categorical features: 6

In [24]:
df.dtypes

ProdTaken                   int64
Age                       float64
TypeofContact              object
CityTier                    int64
DurationOfPitch           float64
Occupation                 object
Gender                     object
NumberOfFollowups         float64
ProductPitched             object
PreferredPropertyStar     float64
MaritalStatus              object
NumberOfTrips             float64
Passport                    int64
PitchSatisfactionScore      int64
OwnCar                      int64
Designation                object
MonthlyIncome             float64
TotalVisiting               int64
dtype: object

In [25]:
# #Discrete features
# discrete_features = [feature for feature in df.columns if (df[feature].unique() < 25)]
# print('Num of categorical features:', len(discrete_features))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [26]:
#Train test split
from sklearn.model_selection import train_test_split
X =df.drop(['ProdTaken'], axis = 1)
y = df['ProdTaken']

In [27]:
X.shape

(4888, 17)

In [28]:
y.shape

(4888,)

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [30]:
#Create column transformer with 3 types of transformers
cat_features = X.select_dtypes(include='object').columns
num_features = X.select_dtypes(exclude='object').columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
        ('OneHotEncoder',oh_transformer,cat_features),
        ('StandardScaler',numeric_transformer,num_features)
    ]
)

In [31]:
preprocessor

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(drop='first'),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'TotalVisiting'],
      dtype='object'))])

In [32]:
#Applying tRANSFORMATION IN TRAINING DATA
X_train = preprocessor.fit_transform(X_train)

In [33]:
#Applying Transformation on test dta
X_test = preprocessor.transform(X_test)

In [34]:
#Model Training
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.ensemble import RandomForestClassifier

In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Define models
models = {
    'Random Forest': RandomForestClassifier(),
    # Add more models here if needed
}

# Initialize a dictionary to store results
results = {}

# Train and evaluate each model
for model_name, model in models.items():
    # Fit the model on training data
    model.fit(X_train, y_train)
    
    # Predict on the test data
    y_pred = model.predict(X_test)
    
    # Calculate accuracy and store in results
    accuracy = accuracy_score(y_test, y_pred)
    results[model_name] = accuracy
    print(f"{model_name} Accuracy: {accuracy:.4f}")

# Display all model results
print("\nModel Performance:")
for model_name, accuracy in results.items():
    print(f"{model_name}: {accuracy:.4f}")

Random Forest Accuracy: 0.9243

Model Performance:
Random Forest: 0.9243